### ISSUE TITLE
Kernal panic

### ISSUE THREAD

**Issue by nikhil19rathore99** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#1]
![WhatsApp Image 2020-07-08 at 15 07 50](https://user-images.githubusercontent.com/32436513/86905854-506af800-c130-11ea-9625-60a9652fafae.jpeg)
After Installing USB WiFi driver and follow the steps in tutorial it gives kernel panic in BigSurr beta 1

**Comment by chris1111** [comment]
I don't think the Programm as nothing to do with this because the kexts is inject by OC so check your setup OC
