### ISSUE TITLE
StatusBar IconSet replacement

### ISSUE THREAD

**Issue by damiandrake0** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#104]
Hi Chris, I am using your Wireless-USB-OC-Big-Sur-Adapter and it works very well.
Is it possible to replace the blue icon with one from your zip? If so, how?
I'm waiting for your answer
Damian_Drake

**Comment by chris1111** [comment]
Hi @damiandrake0 
Do you have a better Icon Set?

**Comment by damiandrake0** [comment]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter
At the end of the page it says StatusBar IconSet replacement.zip

**Comment by chris1111** [comment]
You can chage the Icon of /Library/Application Support/WLAN
Right clic to StatusBarApp /Show package contents /Resources
Copy and replace all Icons then Logout the mac, after login the Icons wil be show

**Comment by damiandrake0** [comment]
Ok, thank you. I advise you to write it on the page
Bye
