### ISSUE TITLE
Hello guys, I just want to say thank you all for the hard work, I just install hackintosh 11.5.2 and this save me a lot of time and effort, thank you again.

### ISSUE THREAD

**Issue by thetrungkien** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#107]
Hello guys, I just want to say thank you all for the hard work, I just install hackintosh 11.5.2 and this save me a lot of time and effort, thank you again.

_Originally posted by @sieutungbi in https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/101_

**Comment by thetrungkien** [comment]
How can you do that, I just installed Big sur 11.5.2 too with TL-WN823n adapter wifi but even effort a lot of time it's not working (it worked well in Catalina 10.15.7)

**Comment by chris1111** [comment]
I have the same adapter and its work ! simply follow the instruction
