### ISSUE TITLE
About SIP and Gatekeeper

### ISSUE THREAD

**Issue by Aerstme** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#119]
Hi

I installed everything and its working fine, amazing. Thanks for all!

can I leave SIP and gatekeeper activated again? just for security I though.

Best regards.

**Comment by chris1111** [comment]
Please try it and tell us if it is possible with OC and tell which macOS

**Comment by chris1111** [comment]
Test my self today on Big Sur 11.6 (20G165)
SIP can be activate after reboot
![Screen Shot 2021-09-15 at 9 08 47 AM](https://user-images.githubusercontent.com/6248794/133440942-5b79de0e-1543-45f0-9eba-845d3bce14b8.png)
