### ISSUE TITLE
It doesn't work with Big Sur 11.0.1 (20B29)

### ISSUE THREAD

**Issue by OsapBender** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#12]
I have been installing your drivers starting from Mac OS Catalina, I have now updated to Big Sur. I uninstalled old drivers and installed new ones, but my macbook does not see the external wifi modem. I am watched your video, you have beta version 11.0, maybe it shouldn't work for me?

**Comment by chris1111** [comment]
The SIP security needs to be fully disable
See this
https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/issues/22#issuecomment-727063587
