### ISSUE TITLE
Can’t install RtWlanU.kext and RtWlanU1827.kext

### ISSUE THREAD

**Issue by chuyin02** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#123]
My system was `MacOS Big Sur 11.5.2`. I have disabled  SIP with setting the value of `crs-active-config ` in `config.plist` to `FF0F0000`. But After installed, there are no such file named `RtWlanU.kext`or `RtWlanU1827.kext` in file `EFI\OC\Kext` and  the program don’t work.

**Comment by chris1111** [comment]
Impossible you have not APFS or HFS partition
