### ISSUE TITLE
Prevent Duplicate Entry on Config.plist

### ISSUE THREAD

**Issue by naufalw** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#124]
Hi sir, i just upgraded to v11, but then my pc cant boot anymore

after i checked the config.plist, i discovered that i have duplicate kext entry there, after i deleted it, my PC can boot again

So my suggestion is, can you add some kinda kext entry duplicate checker ?

Thanks in advance

**Comment by chris1111** [comment]
Yes you right, I will do this
thanks for the catch

**Comment by chris1111** [comment]
This is Done
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/releases/tag/V11
