### ISSUE TITLE
My EFI not working after Install v11

### ISSUE THREAD

**Issue by mhkanon** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#127]
I using "Update 15 Sept 2021 Release V11 adapt for latest macOS Big Sur 11" which works fine. But release version "Update 23 Sept 2021 Release V11 correction delete Entry in config if exist" my EFI not working. My macOS not loading after install it. My macOS details are in the attachment
![Screenshot 2021-09-28 at 11 43 14 AM](https://user-images.githubusercontent.com/24652688/135030083-030b1340-9492-4a73-af88-3318beee9845.png)
.

**Comment by chris1111** [comment]
If you use update program you aways need to uninstall first

**Comment by chris1111** [comment]
EDIT **

Anyway I have atready  test this V11 release before  release it
There is no such a issue with this, I just test now and I show you from picture

**config.plist from Xcode**
![Screen Shot 2021-09-28 at 7 32 04 AM](https://user-images.githubusercontent.com/6248794/135079305-c422dcbf-8b34-428f-9b50-825d349c05e3.png)

**config.plist from OpenCore Configurator**
![Screen Shot 2021-09-28 at 7 32 48 AM](https://user-images.githubusercontent.com/6248794/135079385-7f8c2589-588c-4ba1-8438-86afe9d36b74.png)

**Boot screen from OpenCore**
![28112925](https://user-images.githubusercontent.com/6248794/135079467-e868ee70-4af5-439c-a10c-bca3c1d6f07d.png)

**WIFI working after reboot**
![Screen Shot 2021-09-28 at 7 37 49 AM](https://user-images.githubusercontent.com/6248794/135079714-47295816-6b99-46d9-a316-536098b95712.png)
