### ISSUE TITLE
Big sur new dlink apapter v4 nt working

### ISSUE THREAD

**Issue by robinrj716** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#13]
Sir i tried ur method bt no succes on archer t2u nano i hot 2 kext afte your package installinion but at network its not showing could u please corrct or update ur files

**Comment by robinrj716** [comment]
Its not same appear like catalina its not shwoing the dlink icon on syetem preference i m using it on oc pls sir fix it pls

**Comment by chris1111** [comment]
t2u nano work since the first beta and work in release this is a known working adapter

**Comment by robinrj716** [comment]
Sir i just install pkg fule and on oc i just disable si so why i cant get it is there anything on my setup n catalina worked great
