### ISSUE TITLE
edimax 7811un Mac os Monterey

### ISSUE THREAD

**Issue by claudiey** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#134]
i've got an Edimax 7811un and a Mac OS X Monterey Beta 9 installed. I've downloaded your v11 install package but even after installation of the program, the system cannot detect my wifi USB. I have another partition with Mac OS X Big Sur on it and used your previous program and the wifi was working ok with Big Sur. Thanks

**Comment by claudiey** [comment]
Hey yes it's working now! I've tried re-booting my computer several times and finally it worked! Thanks!

**Comment by WXC2408** [comment]
What did you use to make this work?
