### ISSUE TITLE
SIP for Monterey 12.1 beta

### ISSUE THREAD

**Issue by MuttakinHasib** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#150]
hey, I'm using **Monterey 12.1 beta** & **OC 0.7.5**

### how can I disable SIP?

**Comment by chris1111** [comment]
csr-active-config ➤ 67000000 
![Screen Shot 2021-11-19 at 1 40 10 PM](https://user-images.githubusercontent.com/6248794/142674636-defe5b7d-0ce1-45cc-8c66-89d32f113c0b.png)

**Comment by MuttakinHasib** [comment]
@chris1111 
when I do like this. my PC does not open any application like system preferences, firefox, about this mac, nothing without finder

**Comment by chris1111** [comment]
Strange behaviour, you have to investigate?

**Comment by MuttakinHasib** [comment]
Is this happening for the beta version ?
Xcode not working, booting time is too long

**Comment by chris1111** [comment]
I have the same value on my Main PC 
csr-active-config ➤ 67000000

Everythings work like a charm for 2 years now

**Comment by MuttakinHasib** [comment]
![IMG_20211120_084435.jpg](https://user-images.githubusercontent.com/44552983/142711897-627722e2-1876-4e4e-ade2-cdbce93ab0fb.jpg)

every time it's waiting here for long time then its boot successfully
