### ISSUE TITLE
Add license and source code

### ISSUE THREAD

**Issue by 266-750Balloons** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#157]
It is unclear what the terms and conditions are of the software (please make it MIT if you can). In addition, I can't look in the source code to see what it's doing. Can you add the source code for these (whether they are actual drivers or shell scripts to patch a package)?

**Comment by chris1111** [comment]
There is no source for this drivers, only some  drivers Realtek on Linux is sources. If you find somwere the source let me known. I create programs for the users of the whole planets with realtek drivers because no wifi company wanted to update the pilots, they send the wifi adapter buyers here
