### ISSUE TITLE
Wireless Icon is not visible on certain backgrounds

### ISSUE THREAD

**Issue by kanthi** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#16]
The Icon is visible only on light background, when in night times changes happen on macOS all icons turn white except wireless icon. Also on certain backgrounds/wallpapers its not visible due to dark icon.

**Comment by chris1111** [comment]
I will fix in couple minutes

**Comment by chris1111** [comment]
Done
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/releases/tag/V5
