### ISSUE TITLE
Cannot boot after running installation script if previous version is already installed

### ISSUE THREAD

**Issue by GeorgePr** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#17]
I installed V6 in a system where I had a previous version already installed (V4). This resulted in duplicate kext records in config.plist, making the system unable to boot. I think the installation script should search the config.plist kext records to find existing kext dictionaries for rtwlanu.kext and rtwlan1827.kext
After removing the duplicate dictionaries, the system boots normally.

**Comment by chris1111** [comment]
You have to Uninstall Software before Installing new update then reboot before install
![Capture d’écran, le 2020-11-30 à 06 53 25](https://user-images.githubusercontent.com/6248794/100607315-c9820c00-32d8-11eb-9ee1-6841055f2956.png)
