### ISSUE TITLE
iCloud drive unable to up/download files

### ISSUE THREAD

**Issue by paralyser** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#175]
Issue with 902.11ac Realtek usb wifi dongle. -ONLY icloud. (Internet, network is working as it has to )
Tested on: Mojave, Catalina -WORKING.  Monterey-NOT working
On Monterey it seems the os is unable to download or upload the files to the icloud drive, if the usb wifi is set as the primary network card. Switching network to my intel maussi card resolves the problem. I have internet on both cards. Tried also with the usb dongle as the only card, same issue. 
bootloader: opencore 0.76
Can anyone confirm?

**Comment by chris1111** [comment]
Confirmed!
