### ISSUE TITLE
Monitor download speed

### ISSUE THREAD

**Issue by madvinegar** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#18]
Is there any way to enable to monitor the download speed? In any network app I try (including the macOs system monitor), the download speed shows as Zero (0). I am currently in big sur, using latest v.6 of your Big Sur app.
I thank you for your great work.

**Comment by ausmbuswinke** [comment]
Disable SIP still necessary in latest Version?
Thanks for all your work.

Regards
Jürgen

**Comment by madvinegar** [comment]
Yes, it is necessary to disable SIP but it is very easy to do with opencore configurator.

**Comment by chris1111** [comment]
> Is there any way to enable to monitor the download speed? In any network app I try (including the macOs system monitor), the download speed shows as Zero (0). I am currently in big sur, using latest v.6 of your Big Sur app.
> I thank you for your great work.

You can see on Safari open the Download Arow
![Capture d’écran, le 2020-12-02 à 06 56 56](https://user-images.githubusercontent.com/6248794/100869951-d1be8080-346b-11eb-9438-fb3aceb50c74.png)

**Comment by madvinegar** [comment]
Thank you for your reply. You are correct, but this only applies if I download something via safari. What if I download an OS update (i..e Big Sur 11.0.2 when it is out), or I download an app via the App Store. There is no way to monitor the download speed.
Can this be fixed?

**Comment by chris1111** [comment]
You can not find download speed from Appstore like **Installer macOS**  because Apple use /private/var/folders
