### ISSUE TITLE
Cant update to 11.6.2 after driver installation

### ISSUE THREAD

**Issue by Aerstme** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#188]
Hi

I installed this driver few weeks ago, but now I cant update the os to 11.6.2, the last time I updated to 11.6.1 I disabled csrutil and uninstalled the driver, this allowed me to update macOS, but now i cant

im using opencore

**Comment by chris1111** [comment]
Update macOS as nothing to do with the drivers
