### ISSUE TITLE
Error: No USB-Wifi Plug in - TP-Link T3U

### ISSUE THREAD

**Issue by mistrb01** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#189]
I followed the instructions.  However, I get the above error message.

TP-Link T3U - AC1300.  I am running Monterey 12.1 on a MacBook Pro 15in, 2016.  I am using a USB-C to USB hub since the MacBook only has USB-C ports.  I also tried a USBC adapter.

The same Wi-Fi adapter works on my MacMini running Monterey 12.1.

**Comment by chris1111** [comment]
So the responsse is USBC not work
