### ISSUE TITLE
Not working in BigSurr beta 1

### ISSUE THREAD

**Issue by nikhil19rathore99** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#2]
I've checked many times but the problem is not in the OC, this USB WiFi works perferctly in macOs 10.15.5 but gives Kernal panic in bigSurr driver used (Wireless USB-OC-Big-Surr-Adapter)
![Screenshot 2020-07-09 at 1 10 19 PM](https://user-images.githubusercontent.com/32436513/87011536-aea5e280-c1e5-11ea-9ec0-c5b6a6e03939.png)
![Screenshot 2020-07-09 at 1 10 02 PM](https://user-images.githubusercontent.com/32436513/87011554-b36a9680-c1e5-11ea-8efb-8ef5dfd01cfb.png)

Also attached config.plist, please take a look at it

[config.plist.zip](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/files/4895251/config.plist.zip)

**Comment by chris1111** [comment]
I don't have any issue on my Hack HP ProDesk 600 G1 also on my MacBook Pro late 2013 no crash since the first days Big Sur release

**Comment by nikhil19rathore99** [comment]
> I don't have any issue on my Hack HP ProDesk 600 G1 also on my MacBook Pro late 2013 no crash since the first days Big Sur release

Then it might the problem from mysids but I've followed as shown in video maybe bigSurr is in Beta that's why it shows
