### ISSUE TITLE
After install v6 Big sur "Memory panic"

### ISSUE THREAD

**Issue by mhkanon** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#20]
I download the Big Sur **Apple** store. After Install big sur everything is working perfectly. When I install V6 and restart I saw verbose are **Memory Panic succeed**. I share my EFI here. Please, check and tell me if I have any problem in my **EFI**

https://drive.google.com/file/d/1DkA2IB0XavV_JDyTGVgtmSv6-ayDLVFL/view

Thank you

**Comment by chris1111** [comment]
the program has nothing to do with your EFI file, it works fine and I see nothing abnormal in your EFI Chek your OC Log and try ti find your issue
