### ISSUE TITLE
Can't get to work Monterey 12.2.1

### ISSUE THREAD

**Issue by EllenHighwater** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#205]
Hi there, have tried everything...disabled SIP security, /usr/sbin/spctl kext-consent add ZYM2ETK3E7 command, securebootmodel disable...all I get is the wifi icon at the top status bar, with a red dot, saying 'No USB WIFI Plugin'...have tried uninstalling, all sorts of combinations...no joy. Can anyone please help?
![Screen Shot 2022-02-26 at 22 26 12](https://user-images.githubusercontent.com/99619596/155861128-0fa9bc65-1be8-46c0-a4f6-f5d15b341299.png)

**Comment by chris1111** [comment]
What is the adapter

**Comment by EllenHighwater** [comment]
Thanks Chris. It's a TP Link Archer T2U Nano...also tried an Archer T2U....system doesn't seem to detect either of them. Running OpenCore Hackintosh on a Dell G5 5500 laptop. Thanks

**Comment by chris1111** [comment]
I dont know whats wrong with this adapater, it is report working for long time a go, or maybe check your OC setup config.plist ?

**Comment by EllenHighwater** [comment]
Thanks. I know that I never disabled CFG lock in the bios for this Hackintosh. Could this have something to do with it? I ....didn't really want to hack my bios, so amended the config.plist accordinglyHere's my config.plist preinstal;
[config.plist.zip](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/files/8149288/config.plist.zip)
Thanks for your help!

**Comment by chris1111** [comment]
This is not a config.plist use with Wireless-USB-OC-Big-On-Adapter

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/207
