### ISSUE TITLE
Can't get kexts to work: system crashes while booting

### ISSUE THREAD

**Issue by RobinS-S** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#209]
Hello,

First of all, thank you for devoting your time to this project. Very useful. I'm not sure if the problem I have is caused by these kexts: but without them my machine boots without problems. The machine restarts after this screen
![dasads](https://user-images.githubusercontent.com/16294492/156946960-3db93c22-101d-4200-9d3d-476d73c9ca7e.jpg)
[opencore-2022-03-06-231955.txt](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/files/8193769/opencore-2022-03-06-231955.txt)
[config.txt](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/files/8193771/config.txt)

I have tried the notarized and normal releases, both don't work. Also tried disabling other kexts that might interfere with these. Running Monterey 12.1. Also tried disabling/enabling SIP.

Does anyone have any idea what could be causing this?

**Comment by chris1111** [comment]
regarding the log the wifi kext as nothing to do with this
