### ISSUE TITLE
Hi, can you please help me with my dell on macOS 10.15.7?

### ISSUE THREAD

**Issue by Techgeek2011** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#210]
Hi there, I have a dell latitude E5540 with macOS Catalina, will this tool work for me? 

Thanks in advance

**Comment by chris1111** [comment]
the tool is not dedicated for specific machine, it is for Specifics Wifi adapters

**Comment by Techgeek2011** [comment]
> the tool is not dedicated for specific machine, it is for Specifics Wifi adapters

Okay, thanks!

**Comment by Techgeek2011** [comment]
I ended up using itlwm and heliport, thanks for your help! :-)
