### ISSUE TITLE
Searching for WPS (RTL8881ETV)

### ISSUE THREAD

**Issue by bahaedin** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#214]
Hi @chris1111 
I hope you doing well.

Please, I can't close this window its start automatically when I login to my os prevent me from choosing my network manually.

When I click in to the icon in status bar or wireless utility , I receive this window automatically Is there a way to stop it from searching WPS

I have a Chinese USB adapter. **(RTL8188ETV)**

![IMG_20220320_101409](https://user-images.githubusercontent.com/57917164/159157838-3dee1cdf-a2df-47ad-a93a-51bfd1629812.jpg)
![IMG_20220320_101344](https://user-images.githubusercontent.com/57917164/159157851-c1a94105-7926-4f86-a918-e5874a2b7179.jpg)

**Comment by chris1111** [comment]
Never see this?? Check the button on USB adapter if is not jam

**Comment by bahaedin** [comment]
There is no button on USB adapter

**Comment by chris1111** [comment]
> There is no button on USB adapter


[
](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/issues/214#issuecomment-1073228531)

**Comment by bahaedin** [comment]
> > There is no button on USB adapter
> 
> Check the router

WPS is already disabled on my router, this happens before connecting to wifi, I don't even have access to enter the password, it redirects me directly to this window.
