### ISSUE TITLE
not working in 11.4(ESP OC)

### ISSUE THREAD

**Issue by itenl** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#219]
`USB-WIFI adapter: COMFAST CF-811AC`

`usb-wifi status`
![image](https://user-images.githubusercontent.com/16585374/162199762-df7ed0a7-5424-473d-a380-236740baa4f4.png)

`csrutil status`

![image](https://user-images.githubusercontent.com/16585374/162199961-8146ce8b-6625-4ab0-84f3-57486f0d728e.png)

[step by step the order](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/issues/168)
in Boot in Recovery
```
csrutil disable
/usr/sbin/spctl kext-consent add ZYM2ETK3E7
```
![image](https://user-images.githubusercontent.com/16585374/162200537-d7d494bb-afbf-422e-b492-44387e8e09ce.png)

![image](https://user-images.githubusercontent.com/16585374/162200969-de528431-4a1d-411d-977c-54e684939634.png)

![image](https://user-images.githubusercontent.com/16585374/162201052-227b4827-fcb8-47fa-8da4-742455f9b1b3.png)

**Comment by chris1111** [comment]
where you see spctl kext-consent for EFI Partition

**Comment by chris1111** [comment]
issue will be delete
