### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by AhmedElshimy1998** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#224]
Today i install your tools with your guide wifi kext work fine but when connect to my wifi connected but internet didn't work but when make a hotspot from my mobile for my wifi and connected to new hotspot network (source my wifi) work fine !
so why didn't work fine with my wifi !

**Comment by chris1111** [comment]
It look like you trying a lots of things, Hotspot, new Hotspot, Wifi, Internet 
Confusing
