### ISSUE TITLE
No reason to disable SIP 

### ISSUE THREAD

**Issue by extremegrief1** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#238]
Forcing the installer to run on Ventura without the SIP check is working as intended, why do you recommend disabling it and Apple Secure Boot? Also, where is the source code?

**Comment by chris1111** [comment]
First of all read the page on GitHub repos before posting issue! you can install SIP enable

**Comment by extremegrief1** [comment]
According to https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/issues/168, you need to first disable SIP, install the package then re-enable it. This is not necessary.

**Comment by chris1111** [comment]
There is no way to install kernel extensions on Big Sur and above without SIP disable

**Comment by chris1111** [comment]
There is no source for this project, All wifi companies have abandoned it as well as Realtek the main builder.
