### ISSUE TITLE
Kernel panic and stuck on booting

### ISSUE THREAD

**Issue by mohammadnt** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#239]
I followed steps for working with sip enabled, but after installation i cant boot to mac or recovery facing this error:
![PXL_20220903_033259018](https://user-images.githubusercontent.com/10488361/188244978-d3e1827c-ae83-443a-9192-27a6dbc90f89.jpg)
Here is my setup:
![PXL_20220903_033501147](https://user-images.githubusercontent.com/10488361/188245034-a10e23f9-68ad-4d5c-bb27-ff5be252ac01.jpg)

**Comment by chris1111** [comment]
Make sur in EFI/OC/kexts your not have a duplicate Extensions RtWlanU.kext, RtWlanU1827.kext
You have to remove also from config.plist

**Comment by mohammadnt** [comment]
I installed [Wireless-USB-Big-Sur-Adapter](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter) and it worked , then uninstalled it. again i tested oc version and checked for not duplicate items , and it worked! thanks
