### ISSUE TITLE
I installed it and restart but it seems doesn't work.

### ISSUE THREAD

**Issue by chris1111** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#242]
I installed it and restart but it seems doesn't work.
v13 supports the rtl8812au ?

_Originally posted by @wonchoinobi in https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/241_

**Comment by chris1111** [comment]
What is the USB adapter brand?

**Comment by wonchoinobi** [comment]
WISE TIGER WT-AC9008

**Comment by wonchoinobi** [comment]
Oh! I figured out!!! +_+ Thank you @chris1111
