### ISSUE TITLE
Possible to add kext in Kernel -Add?

### ISSUE THREAD

**Issue by mswgen** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#243]
Is it possible to add the kext in OC config not /L/E? If it's possible there might be no need to disable sip.

**Comment by chris1111** [comment]
> Is it possible to add the kext in OC config not /L/E? If it's possible there might be no need to disable sip.


For Wireless-USB-OC-Big-Sur-Adapter the kext is add in OC but if you use `Notarized `method you need to use Wireless USB Big Sur Adapter with kext installed in /L/E

**Comment by mswgen** [comment]
Then it would be a good idea to provide unpacked kexts to use with OC. (The repo name is Wireless USB **OC** Big Sur Adapter.)
