### ISSUE TITLE
Asus WL-160N (RT2870)

### ISSUE THREAD

**Issue by Petros00** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#254]
Hi,

I have an Asus wl-160n stick that works perfectly with your drivers on my desktop with Catalina.

I just can't get it to work on my laptop(which is where I need it the most) that runs Big Sur 11.2.

I notice that my device id I not in either kext (0x1731). I tried adding it but got no results.

The installation goes as expected(SIP off), kexts are placed in OC folder, app loads on startup but says no USB detected.

Should I gather that it is not supported and move on?

Thanks a lot for your terrific work:)

**Comment by chris1111** [comment]
If the adapter works in Catalina it should work on macOS 11, 12 and 13
Try another USB port or check your EFI OpenCore because as I told you if it works on the PC it must work on the alptop
