### ISSUE TITLE
Sometimes WiFi app has problem to start during Startup phase.

### ISSUE THREAD

**Issue by thematrix86** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#279]
Sometimes the application has difficulty starting up during the startup phase of my Mac Pro. The rainbow colored wheel is visible if I hover over it with the mouse cursor, I have to reboot to get around the problem. 
Installed the latest OC V16 version.

Mac Pro 5.1
Big Sur 11.7.3
Wifi Adapter Cudy AC1300

**Comment by chris1111** [comment]
on which macOS?

**Comment by thematrix86** [comment]
Big Sur 11.7.3

**Comment by chris1111** [comment]
Probably a graphics issue from OCLP because thats not happend on non patched system

**Comment by thematrix86** [comment]
Thank you for your answer Chris, but i think Is not only a graphic issue because the whole application Is stuck. It means that It cannot connect to wifi.

**Comment by chris1111** [comment]
Probably other root patch system? 
I will have to close this thread because here we have not corrected this kind of problem linking to OCLP
I tell you that WifiUtility never had such a problem on an unpatched system
