### ISSUE TITLE
Only working for few seconds. 

### ISSUE THREAD

**Issue by TharinduX** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#282]
Hey Chris, 

I have Realtek RTL8188EU wireless lan 80211n, I installed this on my Hackintosh, and I can join the WiFi but when browsing internet it works only few seconds and then pages not loading anymore. I changed the USB and re-installed couple of times. Kindly help me out.

Thanks

**Comment by chris1111** [comment]
There is no relation with the program, its relate to your adapter or rooter
