### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by AlphaNecron** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#294]
Is this compatible with T2UB (T2U with Bluetooth)? It's already compatible with T2U but I'm wondering whether it can be used with Bluetooth variant.

**Comment by chris1111** [comment]
No Apple Bluetooth is compatible only with Broadcom Bluetooth

**Comment by AlphaNecron** [comment]
Oh, thanks.

**Comment by mxscowc1ty** [comment]
> Is this compatible with T2UB (T2U with Bluetooth)? It's already compatible with T2U but I'm wondering whether it can be used with Bluetooth variant.

Bluetooth will work with this USB if you add "BrcmBluetoothInjector" and "BlueToolFixup" kexts, but only with Wi-Fi turned off. I don't know, if it's an application's bug, or the adapter itself, or the system-liminations. 

When Bluetooth is on, you can't work with StatusBarApp anymore — if you'll try, it will break all connections and still show as active, but will stop searching for and connecting to devices.
![1](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/55637151/d5dc0340-cd93-428f-84e4-650a0e5a3639)
![2](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/55637151/45981498-faa2-4fb7-aafb-d6fd765f176f)

**Comment by AlphaNecron** [comment]
Thanks, but I got a AX210, no need this one anymore.

**Comment by chris1111** [comment]
> Bluetooth will work with this USB if you add "BrcmBluetoothInjector" and "BlueToolFixup" kexts, but only with Wi-Fi turned off. I don't know, if it's an application's bug (@chris1111 mayb you can give us a hint), or the adapter itself, or the system-liminations.
>

Try with
```
BlueToolFixup.kext
BrcmFirmwareData.kext
BrcmPatchRAM3.kext
```

dont use BrcmBluetoothInjector
?

**Comment by mxscowc1ty** [comment]
> Try with
> ```
> BlueToolFixup.kext
> BrcmFirmwareData.kext
> BrcmPatchRAM3.kext
> ```
> 
> dont use BrcmBluetoothInjector ?

Tysm for your reply!

Unfortunately, changed kexts, but the result still the same — Bluetooth and Wi-Fi can't work together, because running the StatusBarApp drops the Bluetooth connection... Perhaps this is an issue with the adapter itself and I'm in any case glad it was able to start up, even though It's not natively supported.

I'm also not demanding that u can fix this, but would be glad if there're any other ideas!

https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/55637151/c1846607-b29b-4905-9f76-20c8e607bb5a

**Comment by chris1111** [comment]
> > Try with
> > ```
> > BlueToolFixup.kext
> > BrcmFirmwareData.kext
> > BrcmPatchRAM3.kext
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > dont use BrcmBluetoothInjector ?
> 
> Tysm for your reply!
> 
> Unfortunately, changed kexts, but the result still the same — Bluetooth and Wi-Fi can't work together, because running the StatusBarApp drops the Bluetooth connection... Perhaps this is an issue with the adapter itself and I'm in any case glad it was able to start up, even though It's not natively supported.
> 
> I'm also not demanding that u can fix this, but would be glad if there're any other ideas!
> 
>  Screen.Recording.2023-09-19.at.23-09-50.mp4

It seem your not using latest Utility because the statusBar App is Blue

**Comment by mxscowc1ty** [comment]
> It seem your not using latest Utility because the statusBar App is Blue

Oh yeah, hadn't noticed, thanks!

Checked with the latest V17 and the same problem.... If it can't be fixed, I don't insist, it's fine)
