### ISSUE TITLE
How to change menu bar icon?

### ISSUE THREAD

**Issue by francisceril** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#30]
Hi, first of thanks for the great work.

How do I change the menu bar icon? The current blue icon is somewhat blurry on my 4K display and it is out of place from other icons being black or white only.

**Comment by chris1111** [comment]
Thanks the Icon is soon /Library/Application Support/WLAN/StatusBarApp.app
Right clic Show Package /Content/Resources 
we have 7 **BarSignal.icns** 
do you please take a screen shot of the status bar
