### ISSUE TITLE
Wifi adapter doesn't work after install

### ISSUE THREAD

**Issue by NISES12** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#308]
Hi @chris1111 i've tried installing this multiple times and both times non of my deices work. i've tried a Edimax 7811UN and a Archer T3U and neither of them are being being found by the software. Macbook air 13 2015 Macos Monterey

**Comment by chris1111** [comment]
I have Archer T3U and Edimax 7811UN working from 10.15 to Sonoma 14
Wireless-USB-OC-Big-Sur-Adapter not work from Software System Update, it work from the bootloader OC

**Comment by NISES12** [comment]
So you’re just going to close the issue without troubleshooting the issue and just saying it works for you even though it doesnt work for me. Great job #sarcasm
