### ISSUE TITLE
Does this driver supports TL-WN722N v3.20?

### ISSUE THREAD

**Issue by stereoDotLuigi** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#309]
I saw tested adapters and I think I will buy
Archer T2U Plus, TL-WN722N or TL-WN825N.

TL-WN722N looked good for me but I have a question.
In TP-Link's website, v3 and v3.20 are different.
And I don't want to buy an adapter that doesn't work with macOS.

I hope you can answer my question. Thank you.

**Comment by stereoDotLuigi** [comment]
The answer is actually a big no. It doesn't support because it doesn't have a macOS driver.

**Comment by chris1111** [comment]
> I saw tested adapters and I think I will buy
> 
> Archer T2U Plus, TL-WN722N or TL-WN825N.
> 
> 
> 
> TL-WN722N looked good for me but I have a question.
> 
> In TP-Link's website, v3 and v3.20 are different.
> 
> And I don't want to buy an adapter that doesn't work with macOS.
> 
> 
> 
> I hope you can answer my question. Thank you.

V3.2.0 is only for windows

V2 and V3 is good for Mac

**Comment by stereoDotLuigi** [comment]
Where can I buy a V2/V3 version of TL-WN722N?
I found this Amazon page, everybody is saying it's V2 or V3.
https://www.amazon.com.tr/TP-Link-TL-WN722N-150Mbps-Kablosuz-Adaptör/dp/9800359850

**Comment by chris1111** [comment]
I think its  V2 ?

**Comment by stereoDotLuigi** [comment]
I just bought it and it works! Thanks to you!
I think my adapter is V4 because in the box it says "Ver: 4.0"
But the FCC-ID says it's V2. Which one should I trust?

**Comment by chris1111** [comment]
See in the  USB 
![IMG_3316](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/6248794/f42425c3-4585-4138-b16e-95a330af5ebd)

**Comment by stereoDotLuigi** [comment]
Well, it's weird but look at these:
![2023-08-11 18 44 44](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/110627763/299361f8-beaf-4541-8a4f-75b464f814aa)
![2023-08-11 18 19 00](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/110627763/34770a3e-cbfd-42b3-9521-13a8811ab6d8)

**Comment by chris1111** [comment]
see
![260056273-34770a3e-cbfd-42b3-9521-13a8811ab6d8](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/6248794/e718d5d3-156d-44b6-b2db-da91e20cd8f2)
