### ISSUE TITLE
Install break my config

### ISSUE THREAD

**Issue by deldavdel** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#31]
Hi !

I just install your app and when it reboot, it is stuck on "OCB:Startimage Failed" I didn't have this issue before. Do you have any idea how can I fix this ?

I am on OC 0.6.6 on Catalina 10.15.7

Thank you !

**Comment by chris1111** [comment]
Sorry but this is an OC issue not a wireless USB Install issue

**Comment by deldavdel** [comment]
Hey,

Thank you for uour answer, I just reinstall MacOS + your app and this time I have "Prelinked Injection RTWLanU.kext - Invalid Parameter.

The two kexts are well enabled in my config.

Thank you

**Comment by chris1111** [comment]
Wait a minute I see now  you trying a Big Sur sosware on Catalina
what are you doing
