### ISSUE TITLE
Ventura 13.6 not working

### ISSUE THREAD

**Issue by pferioli** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#313]
Hi to all, i've disabled SIP with csrutil disable from secure boot mode and also  executed `sudo spctl --master-disable`i was able to install "Wireless USB Big Sur Adapter-V17" package and i have and icon in the tool bar, but it sais "No Usb-Wifi connection to card", the adapter is a HANA M-C003 adaper based on RTL8188 chipset, any help with be much more appreciated

**Comment by chris1111** [comment]
There are a lot of RTL8188 ?
There are many RTL8188 ' What I know is that
 (RTL8188CU) and (RTL8188CUS) only work for a old macOS X Lion 10.7

**Comment by Ragnarok93** [comment]
Same here, my adapter worked on 13.5 but is broken on 13.6 even with a fresh install.

**Comment by chris1111** [comment]
> Same here, my adapter worked on 13.5 but is broken on 13.6 even with a fresh install. "No USB Wifi Plug In"

All of my adapter work on 13.6 
I have 8 USB Realtek

**Comment by Tetoalb** [comment]
[image0.png]

How do I stop these emails?!
Sent from my iPhone

On Sep 26, 2023, at 7:20 PM, chris1111 ***@***.***> wrote:

﻿

Closed #313<https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/issues/313> as completed.

**Comment by Ragnarok93** [comment]
Fixed. User error, forgot to add the kexts from Master
