### ISSUE TITLE
Unable to boot into Big Sur after installing and the restart 

### ISSUE THREAD

**Issue by eKeiran** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#319]
Hi! So basically I have a TL-link WN725N V3 usb adapter and I wanted to make it work on my Big Sur hackintosh with opencore so I disabled SIP and installed this wireless OC big sur adapter driver as in the video then it asked for a restart but I can't boot into Big Sur after the restart. Nothing shows up but a black screen, the apple logo doesn't come up. I tried enabling the SIP and booting but that didn't work either. I also added the two kexts from master but no luck. Secure boot is disabled. 
I'm not sure how to get the program log if I can't boot. Please help. 

Here's my system info:  
![IMG-20231219-WA0083.jpg](https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/assets/34791715/e3dd0252-aed0-4c50-86d7-f45d138b4b37)

**Comment by chris1111** [comment]
The kexts installed by the program cannot at any time prevent the boot, however incorrect handling of the kexts can do so so I advise you to review your config.plist and your installation.
The boot logs can be recovered by OpenCore and this has nothing to do with the program
In addition, you have to hide your serial number when showing an image on the WEB.
