### ISSUE TITLE
COMFAST CF-812AC V2

### ISSUE THREAD

**Issue by andersomdutra** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#323]
Is this adapter really not compatible?

I tried both the installer here and the one on the official comfast website and nothing worked.

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/73

**Comment by andersomdutra** [comment]
> #73

Doesn't it hurt what I have to be a V2?

Because there are two models:
COMFAST CF-812AC
COMFAST CF-812AC V2

I'll ask him how he did it.

**Comment by chris1111** [comment]
V2 probably not support in macOS ,only windows I think?

**Comment by andersomdutra** [comment]
According to the specifications, yes, it is compatible.

[https://en.comfast.com.cn/index.php?m=content&c=index&a=show&catid=13&id=241](url)
