### ISSUE TITLE
Can't login to App Store

### ISSUE THREAD

**Issue by tuancuong92** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#325]
Hi, I am using V16. I fixed iService running smoothly but I cant login to the App Store.
Only the App Store, Music App works perfectly.
I tried another Wifi solution and I can log in to the App Store normaly.
I'm on Sonoma 14.3

**Comment by chris1111** [comment]
No Issue here login to the AppStore, You need sign in Account before login AppStore
