### ISSUE TITLE
Tenda W311MI not working on big sur

### ISSUE THREAD

**Issue by Wired-cell** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#339]
Hi, I followed your guide and disabled sip and the program installed successfully but upon rebooting it says no usb plugged in. I have seen a discussion where someone states it is working but I could not get mine to work. Could you perhaps Tell me the version of macos that supports it ?

**Comment by chris1111** [comment]
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter/discussions/62#discussioncomment-9387217

**Comment by Wired-cell** [comment]
But there is no answer in the discussion . I wanted to know the version of big sur .
