### ISSUE TITLE
Hackintosh on 14.4.1 on ryzen has to run installer to get the wifi icon

### ISSUE THREAD

**Issue by Hackintoshuser** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#340]
So ive been using this for a while on my hackintosh ryzen 3700u with igpu everytime i boot up i have to run the installer to show the wifi icon to use wifi? i have SIP disabled fully in my nvram and i used apple recovery to disable it?

**Comment by chris1111** [comment]
Try changing usb port

**Comment by Hackintoshuser** [comment]
I found out the problem on the opencore version of this you have to run the installer everytime you boot
