### ISSUE TITLE
TL-WN822N(EU) Ver:5.0 Works but can't use location services

### ISSUE THREAD

**Issue by kapasifulop** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#341]
I'm using a TL-WN822N(EU) Ver:5.0 with MacOS Ventura (13.6.7) and it works with this app, but when I try to go to the Apple Maps i still get an error about your location cannot be shown because I dont have wifi. But In the system settings I cannot enable Wifi, BUT I have it from this app.

**Comment by chris1111** [comment]
Did you try [this](https://github.com/chris1111/Wireless-USB-Big-Sur-Adapter/blob/master/Fix_Apple_Services.md)

**Comment by kapasifulop** [comment]
Yes

**Comment by chris1111** [comment]
ok
