### ISSUE TITLE
Working on 1 machine but not the other

### ISSUE THREAD

**Issue by thgilciffart** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#346]
I installed it on my intel based machine Surface Laptop 3, it worked perfectly as expected however when I installed it on my skylake based machine, it doesn't seem to work. The csr-active-config is the same and however on the skylake machine, the usb isn't detected by the program. I can see it within System information --> usb

**Comment by thgilciffart** [comment]
nvm it's because I used a usb to boot instead of ssd

**Comment by chris1111** [comment]
Maybe also install on USB Disk?
