### ISSUE TITLE
NO USB-WIFI PLUG IN

### ISSUE THREAD

**Issue by zhangxiaofan1992** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#349]
Macos 13.6.7
oc 1.0.0
After I installed it（Wireless.USB.OC.Big.Sur.Adapter-V17）, it prompted  NO USB-WIFI PLUG IN
My usb network card is comfast cf-811ac v3
I'm very worried about this problem now

**Comment by chris1111** [comment]
comfast cf-811ac v3 It support only Windows
https://en.comfast.com.cn/index.php?m=content&c=index&a=show&catid=13&id=243
