### ISSUE TITLE
Wireless USB OC Adapter and OC 0.6.7

### ISSUE THREAD

**Issue by evasilis** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#35]
Hi there

is it safe to install V.7 on OC 0.6.7?

Thanks

**Comment by Cimmerian-Iter** [comment]
yeah just disable sip and install the package. I installed it normally on my OC 0.6.7 and it works fine

**Comment by evasilis** [comment]
Wonderful! Thanks!
