### ISSUE TITLE
5Ghz Wifi band is not showing up in wifi list.

### ISSUE THREAD

**Issue by 92EPk** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#350]
Hello,
I have a wireless tp-link tl-wn822n ver:5.0
in my router, I have two-band wifi 2.4Ghz and 5Ghz, the 2.4Ghz showing up in the Wi-Fi list but I need to connect my PC to 5Ghz the problem is it's not showing up in the Wi-Fi list in PC "Hackintosh" but showing up in any mobile device.

**Comment by chris1111** [comment]
Try turn On / Off WIFI in Status Bar App

**Comment by 92EPk** [comment]
> Try turn On / Off WIFI in Status Bar App

I did and still no way to make it show up the 5Ghz on PC
