### ISSUE TITLE
ugreen cm448 not working

### ISSUE THREAD

**Issue by wuzhanshuo** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#351]
Hi, 

i've already turned sip off in recovery mode. 
all the kexts are in the kexts folder and enabled in config.plist
after all the program still shows me "no usb-wifi plug in"
device: surface pro 6 i5-8250u kaby lake
os: ventura 13.5
i wonder what's wrong. 
anyway thanks for your program

**Comment by chris1111** [comment]
I dont know whats wrong because this utility is made for PC and Laptop
