### ISSUE TITLE
Wireless usb adapter

### ISSUE THREAD

**Issue by Guiviera09** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#355]
Hello Chris, you are a very fierce guy at what you do, and I wanted to know if you can help me, I have a wireless USB dongle rtl8188etv because my wifi card is not compatible with MacOs and I also think that this dongle is not, do you have any method or kext that makes this USB dongle work?

**Comment by chris1111** [comment]
Hi @Guiviera09  Sorry there is no way to make it work this drivers never working in macOS

**Comment by Guiviera09** [comment]
ok thank you very much for the tip, I bought a native wifi card BCM94360CS2, let me just clear up a doubt, with this can I activate everything on it? wifi, airdrop and bluetooth?
