### ISSUE TITLE
Cannot get imessage to send messages

### ISSUE THREAD

**Issue by Wired-cell** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#363]
I tried using the fix but every time I make a virtual bridge, if usb adapter is set as the first choice, the connection appears as connected and the messages are not delivered. If I choose my ethernrt as the forst choice, I cannot connect to the internet if it shows self connected ip.

**Comment by chris1111** [comment]
in which macOS

**Comment by Wired-cell** [comment]
Monterey 12.6

**Comment by Wired-cell** [comment]
Any solutions or fixes that I can try ? Also, does horndis tethering work if I cannot get the virtual bridge to send messages ?

**Comment by chris1111** [comment]
I dont know I am not control Apple Update the test is mad on particular mac version then when is change probably its not work. So no there is no fix on my side.
