### ISSUE TITLE
rtl8188gu

### ISSUE THREAD

**Issue by y655r** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#40]
Thanks for your contribution. I just bought a USB dongle (rtl8188gu,ID 0bda:b711 Realtek）. I wonder if your "Wireless-USB-OC-Big-Sur-Adapter" will work on the laptop(surface pro3, big sur 11.0.1, opencore) or not. Thanks again.

**Comment by chris1111** [comment]
Not support

**Comment by y655r** [comment]
Thanks, what about RTL8188EUC, support or not?

**Comment by chris1111** [comment]
View list
https://github.com/chris1111/Wireless-USB-OC-Big-Sur-Adapter#known-working-and-testing-adapter
