### ISSUE TITLE
Problem TP-LINK TL-WN823N 

### ISSUE THREAD

**Issue by Giandomenico51** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#44]
Hi, I have installed Big Sur on i5-3470, 8GB RAM, GTx 710, and TP-LINK TL-WN823N wifi adapter. I have installed the kext for the wifi "wireless USB OC big sur adapter - V7" but I have problems. The wifi works intermittently, sometimes it works and sometimes it doesn't, sometimes it only works for 30 seconds, others for 5 minutes, but I never have a stable connection. How can I solve?

**Comment by chris1111** [comment]
Router issue because I have the same adapter without issue
