### ISSUE TITLE
Problem with big sure update "11.3.1", Kernel panic "can't perform kext scan: no kext summary" 

### ISSUE THREAD

**Issue by J1n0** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#48]
It was working like charm on catalina and big sure, and after update to big sur 11.3.1 not working at all with tp-link wn822n v5.
I tried everything 😪
Clean install with oc 6.5, 6.8 same problem.

Kernel panic "can't perform kext scan: no kext summary" 
![20210504_094637](https://user-images.githubusercontent.com/53805165/116975150-77964580-acbf-11eb-8938-09d675735fc6.jpg)

**Comment by chris1111** [comment]
I am surprised to hear this kind of thing, OC has no problem with injecting kext on any macOS version;  for my test here I am using OC 0.6.9 without any problem

![Capture d’écran, le 2021-05-04 à 07 05 39](https://user-images.githubusercontent.com/6248794/116995329-eff10c80-aca7-11eb-9227-1ffc1d38cab6.png)
![Capture d’écran, le 2021-05-04 à 07 08 02](https://user-images.githubusercontent.com/6248794/116995345-f3849380-aca7-11eb-88e9-7626fbf55e57.png)
