### ISSUE TITLE
Is there any way to force 5Ghz Wifi?

### ISSUE THREAD

**Issue by binxk** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#5]
My Adapter [TP-Link Archer T2U] automatically connects to 2,4Ghz but this is too slow so I want to use 5Ghz. I can't disable 2,4Ghz because of other devices that are incompatible with 5Ghz.
In Windows I can set the Wifi-Mode to 801.11ac so I thought it would be possible to get this in macOS working too.

**Comment by chris1111** [comment]
This issue is already talk https://github.com/chris1111/Wireless-USB-Adapter/issues/66 I don't think its possible
