### ISSUE TITLE
Kext dosent show up

### ISSUE THREAD

**Issue by Lawrence2231** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#54]
Hey, im Using OpenCore and when i İnstall it, the kext dosent show up in OC Configuratior and EFI>OC>Kext. SIP is disabled too. Why this is happening?

**Comment by Human7900** [comment]
It happens when the EFI partition of the drive is already mounted. Try to unmount EFI partition.

**Comment by aleixsr** [comment]
> It happens when the EFI partition of the drive is already mounted. Try to unmount EFI partition.

That's it, worked like a charm!
