### ISSUE TITLE
Install Succeeds, but kext not copied / configured

### ISSUE THREAD

**Issue by arrmo** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#9]
Hi,

The install from v4 (the latest, right?) successfully completed, and I restarted - but no kext inside OC, and not in the plist => thinking this is a path related thing (I don't have a directory named ESP, which I think it may be looking for?).

Is there a way to manually install, to see if the driver works?

Thanks!

**Comment by chris1111** [comment]
this never happens it's practically impossible
