### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by titust1** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#90]
Using Archer T3U Plus, I installed it on Catalina, but after rebooting and plugging the adapter, it says: "No USB-Wifi Plug in" when clicking on the upper icon. The USB Hub shows a 802.11ac NIC (Realtek based) BUT there's no WIFI adapter showing in Syst Pref / Network. Any ideas? BTW I tried all the 3 latest driver releases 9, 8 and 7.

**Comment by chris1111** [comment]
Catalina !
This project support only Big Sur and Monterey Read the page

**Comment by titust1** [comment]
Yes but not in Catalina
