### ISSUE TITLE
The program conflicts with the keyboard

### ISSUE THREAD

**Issue by Lapp-coder** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#91]
Hi, first of all I want to thank you for what you do. Secondly, I want to tell you about a problem I'm having. After installing the Wireless-USB-OC-Big-Sur-Adapter, the Internet worked, but the keyboard started to disconnect after a couple of seconds after logging into the user. It took me a long time to figure out what was wrong with it, but it turns out that it is because of the installation of the above that it refuses to work. After uninstalling that software, the keyboard works again. Can you tell me what the problem might be?

**Comment by chris1111** [comment]
this program as nothing to do with any macOS device disfonctionement
