### ISSUE TITLE
Virtualbox support

### ISSUE THREAD

**Issue by alitteration** [chris1111/Wireless-USB-OC-Big-Sur-Adapter#96]
Hello,

I'm on BIg Sur and I tried everything as the guide but my TL-832N V2 is still not responding or blinking.

Are there any plans to support VIRTUALBOX?

Many thanks

**Comment by chris1111** [comment]
Hey I have the TL WN823N V2 its work

**Comment by alitteration** [comment]
Thank you but I'm testing on virtual box not on hackintosh and It doesn't seem to work somehow. All I did was installed the software and restarted after disabling SIP. Anything else I should be doing on "Virtualbox" ?
